# Client-Server Communication

Brief overview of some communications sequences between the backend and the Client

## First Access and Login / User Authentication

@startuml
'https://plantuml.com/sequence-diagram

'autonumber
'skinparam responseMessageBelowArrow true

Actor "eMail" as EMailClient order 10
Actor "JS Frontend" as Client order 10
participant "Application" as Server order 20
collections "Server-API" as API order 30

group "application.py" [Providing JS compiled frontend]
    Client -> Server: /
    Client <- Server: Jinja2Templates Response /index.html
    end

group "auth/auth.py" [User Login]
    Client -> API: /api/auth/token - OAuth2PasswordRequestForm
    EMailClient <- API: n-character Validation Code
    Client <- API: TokenPRM
    |||
    Client -> API: /api/auth/token/verify - TokenVerificationCodePPM
    Client <- API: TokenValidPRM
    |||
    Client -> API: /api/auth/token/??? -
    Client <- API: ValidUserTokenValidPRM
    end
@enduml
